name: Coverage Summary no PR

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Give permission to Gradlew
        run: chmod +x gradlew

      - name: Create Wrapper
        run: ./gradlew wrapper

      - name: Build e testes + cobertura
        run: ./gradlew clean test jacocoTestReport

      - name: Gerar Cobertura Cobertura XML
        # dependendo do plugin, ajuste o caminho abaixo
        run: mv build/reports/jacoco/test/jacocoTestReport.xml coverage.xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage.xml'
          badge: true
          format: 'markdown'
          output: 'file'

      - name: Comentar cobertura no PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: code-coverage-results.md
          recreate: true
