name: CI com Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11', '17', '23' ]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Give permission to Gradlew
        run: chmod +x gradlew

      - name: Create Wrapper
        run: .\gradlew wrapper

      - name: Build e testes com JaCoCo
        run: ./gradlew clean test jacocoTestReport

      - name: Upload para Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true